version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command:
      - "--replSet"
      - "rs0"
      - "--bind_ip_all"
      - "--keyFile"
      - "/etc/mongodb/keyfile"
      - "--auth"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwer123!@#
      MONGO_INITDB_DATABASE: maple
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-keyfile:/etc/mongodb/keyfile:ro
    healthcheck:
      test: mongosh --eval 'db.adminCommand("ping")' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data: